# Generated by Django 3.1.2 on 2020-10-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eaf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='DEFAULT VALUE', max_length=500)),
                ('inventory', models.IntegerField(default=200)),
                ('price', models.IntegerField(default=100)),
                ('chemical_composition', models.IntegerField(default=15)),
            ],
        ),
    ]
