# Generated by Django 3.1.2 on 2020-10-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eaf', '0002_commodity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='chemical_composition',
            field=models.IntegerField(default=[{'element': models.IntegerField(primary_key=True, serialize=False), 'name': models.CharField(default='DEFAULT VALUE', max_length=500)}]),
        ),
    ]
