# Generated by Django 3.1.2 on 2020-10-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eaf', '0004_auto_20201026_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='chemical_composition',
            field=models.IntegerField(default=12),
        ),
    ]
