# Generated by Django 3.0.5 on 2020-04-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_fav_song'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fav_song',
        ),
        migrations.AddField(
            model_name='song',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
