# Generated by Django 3.2.4 on 2021-06-25 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mobile_info',
            new_name='Electronics',
        ),
    ]
