# Generated by Django 3.2.4 on 2021-06-25 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile', '0002_rename_mobile_info_electronics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Electronics',
            new_name='Mobile',
        ),
    ]
