# Generated by Django 3.2.4 on 2021-06-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coronamodel',
            name='j_data',
            field=models.JSONField(),
        ),
    ]
