# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 18:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_column='created', default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(db_column='updated', default=django.utils.timezone.now, editable=False)),
                ('ocassionName', models.CharField(blank=True, max_length=45, null=True)),
                ('ocassionDate', models.DateField(blank=True, null=True)),
                ('assetType', models.CharField(blank=True, choices=[('land', 'Land'), ('building', 'Building'), ('equipment', 'Equipment')], default='equipment', max_length=20, null=True)),
                ('dateOfDonation', models.DateField(blank=True, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('subType', models.CharField(blank=True, max_length=20, null=True)),
                ('assetLocation', models.CharField(blank=True, max_length=150, null=True)),
                ('dateOfRegistration', models.DateField(blank=True, null=True)),
                ('extent', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, db_column='createdBy', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donationasset_created_by', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Organisation')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updatedBy', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donationasset_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DonationCash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_column='created', default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(db_column='updated', default=django.utils.timezone.now, editable=False)),
                ('ocassionName', models.CharField(blank=True, max_length=45, null=True)),
                ('ocassionDate', models.DateField(blank=True, null=True)),
                ('receiptNo', models.CharField(blank=True, max_length=15, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('instruementDetails', models.CharField(blank=True, max_length=45, null=True)),
                ('dateOfDonation', models.DateField(blank=True, null=True)),
                ('notes', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, db_column='createdBy', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donationcash_created_by', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Organisation')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updatedBy', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donationcash_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DonationKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_column='created', default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(db_column='updated', default=django.utils.timezone.now, editable=False)),
                ('ocassionName', models.CharField(blank=True, max_length=45, null=True)),
                ('ocassionDate', models.DateField(blank=True, null=True)),
                ('material', models.CharField(blank=True, max_length=45, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('units', models.CharField(blank=True, max_length=5, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('certifiedBy', models.CharField(blank=True, max_length=30, null=True)),
                ('dateOfDonation', models.DateField(blank=True, null=True)),
                ('notes', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, db_column='createdBy', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donationkind_created_by', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Organisation')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updatedBy', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donationkind_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DonationService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_column='created', default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(db_column='updated', default=django.utils.timezone.now, editable=False)),
                ('capacity', models.CharField(max_length=30)),
                ('fromDate', models.DateField(blank=True, null=True)),
                ('toDate', models.DateField(blank=True, null=True)),
                ('ocassionName', models.CharField(blank=True, max_length=45, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='createdBy', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donationservice_created_by', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Organisation')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updatedBy', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donationservice_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
