# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 11:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import member.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Member',
            name='calendar_type',
            field=models.CharField(max_length=15, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='Member',
            name='maasam',
            field=models.ForeignKey(db_column='maasam', blank=True, to='member.MaasamType', null=True)
        ),
        migrations.AddField(
            model_name='Member',
            name='paksham',
            field=models.ForeignKey(db_column='paksham', blank=True, to='member.PakshamType', null=True)
        ),
        migrations.AddField(
            model_name='Member',
            name='tithi',
            field=models.ForeignKey(db_column='tithi', blank=True, to='member.TithiType', null=True)
        ),
        migrations.AddField(
            model_name='Member',
            name='raasi',
            field=models.ForeignKey(db_column='rasi', blank=True, to='member.RasiType', null=True)
        ),
        migrations.AddField(
            model_name='Seva',
            name='calendar_type',
            field=models.CharField(max_length=15, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='Seva',
            name='maasam',
            field=models.ForeignKey(db_column='maasam', blank=True, to='member.MaasamType', null=True)
        ),
        migrations.AddField(
            model_name='Seva',
            name='paksham',
            field=models.ForeignKey(db_column='paksham', blank=True, to='member.PakshamType', null=True)
        ),
        migrations.AddField(
            model_name='Seva',
            name='tithi',
            field=models.ForeignKey(db_column='tithi', blank=True, to='member.TithiType', null=True)
        ),
        migrations.AddField(
            model_name='Seva',
            name='raasi',
            field=models.ForeignKey(db_column='raasi', blank=True, to='member.RasiType', null=True)
        ),
    ]
