# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_lunarsolar_calender'),
        ('member', '0003_auto_20160315_0631'),
        ('member', '0002_donation'),
    ]

    operations = [
    ]
