# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.CharField(editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_valid',
            field=models.BooleanField(db_column='isValid', default=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='mid',
            field=models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='member.Member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='calendar_type',
            field=models.CharField(choices=[(b'lunar', b'Lunar'), (b'solar', b'Solar'), (b'default', b'Default')], default='default', max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.CharField(editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='created_by',
            field=models.CharField(blank=True, db_column='createdBy', editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='updated_by',
            field=models.CharField(blank=True, db_column='updatedBy', editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seva',
            name='calendar_type',
            field=models.CharField(choices=[(b'lunar', b'Lunar'), (b'solar', b'Solar'), (b'default', b'Default')], default='default', max_length=15),
        ),
        migrations.AlterField(
            model_name='seva',
            name='id',
            field=models.CharField(editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seva',
            name='mid',
            field=models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, related_name='sevas', to='member.Member'),
        ),
        migrations.AlterField(
            model_name='sevaaddress',
            name='id',
            field=models.CharField(editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sevaaddress',
            name='sid',
            field=models.OneToOneField(db_column='sid', on_delete=django.db.models.deletion.CASCADE, related_name='seva_address', to='member.Seva'),
        ),
        migrations.AlterField(
            model_name='sevacategory',
            name='id',
            field=models.CharField(editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
