# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_isActive'),

    ]

    operations = [
        migrations.CreateModel(
            name='GroupName',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'groupNames',
            },
        ),
        migrations.CreateModel(
            name='GroupData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('gid', models.ForeignKey(db_column='gid', on_delete=django.db.models.deletion.CASCADE, to='member.GroupName')),
                ('surname', models.CharField(blank=True, max_length=63, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('mobile', models.CharField(blank=True, max_length=24, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, db_column='created')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, db_column='updated')),
                ('created_by', models.ForeignKey(related_name='groupdata_created_by', db_column='createdBy', blank=True, editable=False, to=settings.AUTH_USER_MODEL, null=True)),
                ('updated_by', models.ForeignKey(related_name='groupdata_updated_by', db_column='updatedBy', blank=True, editable=False, to=settings.AUTH_USER_MODEL, null=True)),

            ],
            options={
                'db_table': 'groupData',
            },
        ),
 ]
