# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('member', '0009_importGroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='raasi',
            new_name='rasi',
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groupdata',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupdata',
            name='name',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='groupname',
            name='id',
            field=models.CharField(max_length=21, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groupname',
            name='name',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[(b'm', b'Male'), (b'f', b'Female'), (b'd', b'Data Not Available')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seva',
            name='id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
