# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_auto_20160702_1148'),
    ]

    operations = [
        migrations.RunSQL(
            '''ALTER TABLE django_admin_log DROP FOREIGN KEY django_admin_log_user_id_c564eba6_fk_auth_user_id''',

            reverse_sql='''ALTER TABLE django_admin_log ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id
                FOREIGN KEY (user_id) REFERENCES auth_user(id)'''),

        migrations.RunSQL(
            '''ALTER TABLE django_admin_log ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_id FOREIGN KEY (user_id) REFERENCES users(id)''',

            reverse_sql='''ALTER TABLE django_admin_log DROP FOREIGN KEY django_admin_log_user_id_c564eba6_fk_users_id'''),
    ]

