# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_custom_user_modify_admin_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationasset',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='donationasset',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='donationcash',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='donationcash',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='donationkind',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='donationkind',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='donationservice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='donationservice',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='groupdata',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='groupdata',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='sponsoritem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sponsoritem',
            name='updated_by',
        ),
    ]
