# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 09:19
from __future__ import unicode_literals

from django.db import migrations, models
from django.contrib.gis.db import models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_assetDonation'),

    ]

    operations = [
        migrations.CreateModel(
            name='Trustee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_column='created', default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(db_column='updated', default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(related_name='trustee_created_by', db_column='createdBy', blank=True, editable=False, to=settings.AUTH_USER_MODEL, null=True)),
                ('updated_by', models.ForeignKey(related_name='trustee_updated_by', db_column='updatedBy', blank=True, editable=False, to=settings.AUTH_USER_MODEL, null=True)),
                ('member',  models.ForeignKey(db_column="member", on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('organisation', models.ForeignKey(db_column='organisation', on_delete=django.db.models.deletion.CASCADE, to='member.Organisation')),
                ('designation', models.CharField(max_length=23, blank=True, null=True)),
                ('department', models.CharField(max_length=35, blank=True, null=True)),
                ('from_tenure', models.DateField()),
                ('to_tenure', models.DateField()),
                ('tenure_active', models.CharField(max_length=15)),
                ('valid', models.CharField(max_length=15)),
                ('active', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'trustee',
            },
        ),
        migrations.CreateModel(
            name='Honorary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_column='created', default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(db_column='updated', default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(related_name='honorary_created_by', db_column='createdBy', blank=True, editable=False, to=settings.AUTH_USER_MODEL, null=True)),
                ('updated_by', models.ForeignKey(related_name='honorary_updated_by', db_column='updatedBy', blank=True, editable=False, to=settings.AUTH_USER_MODEL, null=True)),
                ('member',  models.ForeignKey(db_column="member", on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('designation', models.CharField(max_length=23, blank=True, null=True)),
                ('department', models.CharField(max_length=35, blank=True, null=True)),
                ('organisation', models.ForeignKey(db_column='organisation', on_delete=django.db.models.deletion.CASCADE, to='member.Organisation')),
                ('date_of_occasion', models.DateField()),
                ('occasion', models.CharField(max_length=40, blank=True, null=True)),
                ('reference', models.CharField(max_length=40, blank=True, null=True)),
                ('dignitary', models.BooleanField()),
            ],
            options={
                'db_table': 'honorary',
            },
        ),
        migrations.CreateModel(
            name='Complimentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_column='created', default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(db_column='updated', default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(related_name='complimentary_created_by', db_column='createdBy', blank=True, editable=False, to=settings.AUTH_USER_MODEL, null=True)),
                ('updated_by', models.ForeignKey(related_name='complimentary_updated_by', db_column='updatedBy', blank=True, editable=False, to=settings.AUTH_USER_MODEL, null=True)),
                ('refered_by', models.TextField()),
                ('occasion', models.TextField()),
            ],
            options={
                'db_table': 'complimentary',
            },
        ), 
    ]

