# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-03 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_trusteeHonoraryComp'),
        ('member', '0013_user_is_admin'),
        ('member', '0011_medicalprofile'),
    ]

    operations = [
    ]
