# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-03 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_auto_20160704_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sevacategory',
            name='created',
        ),
        migrations.RemoveField(
            model_name='sevacategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sevacategory',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='sevacategory',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='sevacategory',
            name='created_at',
            field=models.DateTimeField(db_column='created', default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='sevacategory',
            name='updated_at',
            field=models.DateTimeField(db_column='updated', default=django.utils.timezone.now, editable=False),
        ),
    ]
