# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-03 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0018_auto_20160704_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_column='created', default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(db_column='updated', default=django.utils.timezone.now, editable=False)),
                ('duration', models.CharField(default='0', max_length=11)),
                ('duration_type', models.CharField(choices=[('day', 'Days'), ('month', 'Months'), ('year', 'Years'), ('life_time', 'Life time'), ('custom', 'Custom')], db_column='durationType', default='life_time', max_length=11)),
                ('status', models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sevacategory',
            name='language',
            field=models.CharField(blank=True, db_column='language', max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='duration',
            name='seva_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duration_seva_category', to='member.SevaCategory'),
        ),
    ]
