# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-06 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0020_duration_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_column='created', default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(db_column='updated', default=django.utils.timezone.now, editable=False)),
                ('event_date', models.DateField()),
                ('status', models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('seva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Seva')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_column='created', default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(db_column='updated', default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=25)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sevacategory',
            name='sponsor_item_type',
        ),
        migrations.RemoveField(
            model_name='sponsoritem',
            name='type',
        ),
        migrations.AddField(
            model_name='sevacategory',
            name='is_puja_held',
            field=models.BooleanField(db_column='isPujaHeld', default=True),
        ),
        migrations.AddField(
            model_name='sevacategory',
            name='show_default_calendar_only',
            field=models.BooleanField(db_column='showDefaultCalendarOnly', default=False),
        ),
        migrations.AddField(
            model_name='sevacategory',
            name='sponsor_item_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.SponsorItemCategory'),
        ),
        migrations.AddField(
            model_name='sponsoritem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='member.SponsorItemCategory'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('event_date', 'seva')]),
        ),
    ]
