# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-06 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0021_auto_20160706_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seva',
            name='smid',
        ),
    ]
