# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-06 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0022_remove_seva_smid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_column='created', default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(db_column='updated', default=django.utils.timezone.now, editable=False)),
                ('brother', models.ForeignKey(blank=True, db_column='brother', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brother', to='member.Member')),
                ('cousins', models.ForeignKey(blank=True, db_column='cousins', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cousins', to='member.Member')),
                ('daughter', models.ForeignKey(blank=True, db_column='daughter', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daughter', to='member.Member')),
                ('father', models.ForeignKey(blank=True, db_column='father', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relativefather', to='member.Member')),
                ('friend', models.ForeignKey(blank=True, db_column='friend', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='member.Member')),
                ('guru', models.ForeignKey(blank=True, db_column='guru', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guru', to='member.Member')),
                ('husband', models.ForeignKey(blank=True, db_column='husband', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='husband', to='member.Member')),
                ('inlaws', models.ForeignKey(blank=True, db_column='inlaws', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inlaws', to='member.Member')),
                ('mid', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, related_name='self', to='member.Member', unique=True)),
                ('mother', models.ForeignKey(blank=True, db_column='mother', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relativemother', to='member.Member')),
                ('sister', models.ForeignKey(blank=True, db_column='sister', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sister', to='member.Member')),
                ('son', models.ForeignKey(blank=True, db_column='son', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='son', to='member.Member')),
                ('wellwisher', models.ForeignKey(blank=True, db_column='wellwisher', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wellwisher', to='member.Member')),
                ('wife', models.ForeignKey(blank=True, db_column='wife', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wife', to='member.Member')),
            ],
            options={
                'db_table': 'Relatives',
            },
        ),
        migrations.AlterField(
            model_name='seva',
            name='id',
            field=models.CharField(editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
