# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0023_auto_20160706_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatives',
            old_name='mid',
            new_name='member',
        ),
        migrations.RemoveField(
            model_name='relatives',
            name='brother',
        ),
        migrations.RemoveField(
            model_name='relatives',
            name='cousins',
        ),
        migrations.RemoveField(
            model_name='relatives',
            name='daughter',
        ),
        migrations.RemoveField(
            model_name='relatives',
            name='father',
        ),
        migrations.RemoveField(
            model_name='relatives',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='relatives',
            name='guru',
        ),
        migrations.RemoveField(
            model_name='relatives',
            name='husband',
        ),
        migrations.RemoveField(
            model_name='relatives',
            name='inlaws',
        ),
        migrations.RemoveField(
            model_name='relatives',
            name='mother',
        ),
        migrations.RemoveField(
            model_name='relatives',
            name='sister',
        ),
        migrations.RemoveField(
            model_name='relatives',
            name='son',
        ),
        migrations.RemoveField(
            model_name='relatives',
            name='wellwisher',
        ),
        migrations.RemoveField(
            model_name='relatives',
            name='wife',
        ),
        migrations.AddField(
            model_name='relatives',
            name='relative_type',
            field=models.CharField(choices=[(b'friend', b'Friend'), (b'wife', b'Wife'), (b'husband', b'Husband'), (b'father', b'Father'), (b'mother', b'Mother'), (b'sister', b'Sister'), (b'brother', b'Brother'), (b'son', b'Son'), (b'daughter', b'Daughter'), (b'Cousin', b'Cousin'), (b'inlaws', b'Inlaws'), (b'wellwisher', b'Wellwisher'), (b'guru', b'Guru')], default='friend', max_length=9),
        ),
        migrations.AddField(
            model_name='relatives',
            name='relativemember',
            field=models.ForeignKey(blank=True, db_column='relativemember', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relativemember', to='member.Member'),
        ),
    ]
