"""
Django settings for disa project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

NAME = 'disad_disa3'
USER = 'root'
PASSWORD = 'bb21'
PORT = 3306
HOST = "127.0.0.1"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'sgsdatta@gmail.com'
EMAIL_HOST_PASSWORD = 'Hanu@123'
EMAIL_PORT = 587 
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'adp@datta.org'
MAX_RECIPIENTS = 20

SMS_GATEWAY_USER = 'kg@dattapeetham.com'
SMS_GATEWAY_PASSWORD = 'datta'
SMS_GATEWAY_SENDER = 'SGDP'
SMS_GATEWAY_ROUTE = 'T'
SMS_GATEWAY_URL =  "http://smsc.biz/httpapi/send?username={}&password={}&sender_id=SGSADP&route=T&phonenumber={}&"
# Override sensitive data here
try:
    from passwords import *
except:
    pass

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'jr^r(7p*_roubq3=a%x_lb2s7_l7v_gry3y2tp($nlpw@-ex!h'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = False
DEBUG = True

ALLOWED_HOSTS = ['*']

# Logging settings for crontab, saves logs in the current folder (disa-py/disa.log)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': './disa.log',
            },
        },
    'loggers': {
        'django_crontab': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}


# Application definition

INSTALLED_APPS = (
    # "suit",
    # 'bootstrap_admin',
    # 'django_admin_bootstrapped',
    'django.contrib.admin',
    # 'adminplus',
    # 'django.contrib.admin.apps.SimpleAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.gis',
    'django.contrib.staticfiles',
    'django_extensions',
    'daterange_filter',
    'rest_framework',
    'import_export',
    'compressor',
    'django_crontab',
    'member',
    'organisation',
    'seva',
    'rolepermissions',
    'social.apps.django_app.default',
    #'social_auth',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'disa.middleware.current_user.CurrentUserMiddleware',
)

ROOT_URLCONF = 'disa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR + '/templates/',
            BASE_DIR + '/disa/templates/',
            BASE_DIR + '/member/templates/',
            BASE_DIR + '/seva/templates/'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social.apps.django_app.context_processors.backends',
                'social.apps.django_app.context_processors.login_redirect',
            ],
        },
    },
]

# List of periodic tasks or jobs
CRONJOBS = [
    ('0 7 * * * ', 'member.tasks.PujaIntimation'), # Execute every day 7 AM
    ('0 6 * * * ', 'member.tasks.AdvancedPujaIntimation'), # Execute every day 6 AM
    ('0 12 * * * ', 'member.tasks.PrasadamDispatchIntimation'), # Execute every day 12 noon
    ('0 0 1 1 * ', 'member.tasks.AnnualReminder'), # Execute once in a year i.e mid night of 1st January
]

WSGI_APPLICATION = 'disa.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.mysql',
        'NAME': NAME,
        'USER': USER,
        'PASSWORD': PASSWORD,
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8',
            'init_command': 'SET '
                            'storage_engine=INNODB,'
                            'character_set_connection=utf8,'
                            'collation_connection=utf8_unicode_ci'
        }
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

# Let this be py-static as on production static folder is owned by php app and nignx rule redirects diff location
COLLECT_STATIC_FOLDER = 'py-static'
STATIC_ROOT = os.path.join(BASE_DIR, COLLECT_STATIC_FOLDER)
STATIC_URL = '/' + COLLECT_STATIC_FOLDER + '/'
#STATIC_URL = '/static/'

# Static folder to hold assets that don't belong to any specific apps
PROJECT_STATIC_FOLDER = 'assets'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, PROJECT_STATIC_FOLDER),
]

LOGIN_URL="/login/"

ROLEPERMISSIONS_MODULE = 'disa.roles'

AUTH_USER_MODEL = 'member.User'
#AUTHENTICATION_BACKENDS = ('member.backends.MyModelBackend',)
AUTHENTICATION_BACKENDS = [#'django.contrib.auth.backends.ModelBackend',
                           'member.backends.MyModelBackend',
                           #'social_auth.backends.facebook.FacebookBackend',
                           #'social_auth.backends.google.GoogleOAuthBackend',
                           #'social_auth.backends.google.GoogleOAuth2Backend',
                           #'social_auth.backends.google.GoogleBackend',
                            'social.backends.facebook.FacebookOAuth2',
                            'social.backends.google.GoogleOAuth2',
                          ]

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # other finders..
    'compressor.finders.CompressorFinder',
)

# In production we want to compress css/javascripts offline
COMPRESS_OFFLINE = True

# For 1.9.2
# MIGRATION_MODULES = {'django_extensions': None}

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    )
}

# REST_FRAMEWORK = {
#     # Use Django's standard `django.contrib.auth` permissions,
#     # or allow read-only access for unauthenticated users.
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
#     ]
# }
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL = '/media/'

SOCIAL_AUTH_DEFAULT_USERNAME = 'new_social_auth_user'

SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = ['https://www.googleapis.com/auth/plus.login',
                                   'https://www.googleapis.com/auth/userinfo.email',
                                   'https://www.googleapis.com/auth/userinfo.profile']

SOCIAL_AUTH_GOOGLE_OAUTH2_USE_DEPRECATED_API = True
SOCIAL_AUTH_GOOGLE_PLUS_USE_DEPRECATED_API = True

# To reset https://console.developers.google.com and login with "disasgsd@gmail.com" email
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '193384541453-f9rlklpu0uvi63k1.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'pQu0kylMf2wn6PP'

# To reset https://developers.facebook.com/apps/ and login with "disasgsd@gmail.com" email
SOCIAL_AUTH_FACEBOOK_KEY = '1095095027200710'
SOCIAL_AUTH_FACEBOOK_SECRET = '923fd58c96dc4fe62f7'

from datetime import date
EVENT_CALENDAR_MAX_DATE = 2019-12-31

