# Generated by Django 3.2.4 on 2021-07-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('free', models.CharField(choices=[('CR', 'Charger'), ('MU', 'Mouse')], default='Charger', max_length=2)),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
