# Generated by Django 3.1.2 on 2020-10-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eaf', '0003_auto_20201026_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='chemical_composition',
            field=models.IntegerField(default=[{'element': {'id': models.IntegerField(primary_key=True, serialize=False), 'name': models.CharField(default='DEFAULT VALUE', max_length=500)}, 'percentage': 12}]),
        ),
    ]
