# Generated by Django 3.2 on 2021-06-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('made_in', models.CharField(max_length=50)),
                ('warranty', models.IntegerField()),
            ],
        ),
    ]
