# Generated by Django 3.2 on 2021-06-23 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mobiles',
            new_name='Mobile',
        ),
    ]
