# Generated by Django 3.2 on 2021-06-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_ac_laptop_tv'),
    ]

    operations = [
        migrations.AddField(
            model_name='ac',
            name='available_status',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='laptop',
            name='os_type',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='mobile',
            name='starting_price',
            field=models.IntegerField(default=None),
        ),
    ]
