# Generated by Django 3.2 on 2021-06-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20210623_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ac',
            name='available_status',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='os_type',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='starting_price',
        ),
    ]
