# Generated by Django 3.0.5 on 2020-10-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eaf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='chemical_composition',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='commodity',
            name='inventory',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='commodity',
            name='name',
            field=models.CharField(default='DEFAULT VALUE', max_length=500),
        ),
        migrations.AddField(
            model_name='commodity',
            name='price',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
