# Generated by Django 3.0.5 on 2020-06-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=100)),
                ('player2', models.CharField(max_length=100)),
                ('player3', models.CharField(max_length=100)),
                ('player4', models.CharField(max_length=100)),
            ],
        ),
    ]
